# neyofit-green.conf

# Frontend - neyofit.in
server {
    listen 80;
    server_name neyofit.in www.neyofit.in;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name neyofit.in www.neyofit.in;

    ssl_certificate /etc/letsencrypt/live/neyofit.in/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/neyofit.in/privkey.pem;

    location / {
        proxy_pass http://127.0.0.1:8916;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}

# Backend - api.neyofit.in
server {
    listen 80;
    server_name api.neyofit.in;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name api.neyofit.in;

    ssl_certificate /etc/letsencrypt/live/neyofit.in/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/neyofit.in/privkey.pem;

    location / {
        proxy_pass http://127.0.0.1:8915;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
